### ISSUE TITLE
モードレスについて

### ISSUE THREAD

**Issue by sho7noka** [smdls/C0#1]
## MainMenu
* コマンドの表示あり
* コマンドの表示なし

上記2点はユーザーの意識を変えてしまうので、コマンドパレットに格納して
メニューから消すのはどうでしょうか？

**Comment by smdls** [comment]
メニューにある操作は、ファイル関連の操作も含め、ウインドウ内に統合する予定です。ファイル関連の操作はモーダルなため、いずれモードレスな設計に書き換えます。
ただ、今はそれ以外の優先度の高い問題を解決するために時間を費やしていて、その部分が解決できるのはもう少し後のバージョンになります。

**Comment by sho7noka** [comment]
このアプリケーションの設計思想上、MainMenuの内容はView内に統合されるだろうなと個人的に予想していたので、納得しました。

CoreとGUIを並行してひとりで開発するのは大変だと思うので、CONTRIBUTING.md とか [gitter](https://gitter.im) の導入を検討下さい。(issueに日本語で要望が流れてくるのをあまり快く思っていないので...)
